import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { VitePWA } from "vite-plugin-pwa";
import { nitro } from "nitro/vite";

export default defineConfig({
  // `npm run dev` (plain `vite dev`) binds to localhost only by default --
  // LAN origins like http://192.168.1.79:5173 need this to be reachable
  // without manually passing --host every time.
  server: {
    host: true,
  },
  // maplibre-gl spins up its vector-tile parser as a Worker, loaded via a
  // relative `new URL(..., import.meta.url)` next to its own bundled file.
  // Vite's dev-mode dependency pre-bundling (esbuild) flattens the package
  // into node_modules/.vite/deps/maplibre-gl.js without ever emitting that
  // companion worker chunk, so the Worker constructor 404s -- vector tiles
  // then never load (map stays blank except any raster fallback layer,
  // silently: no MapLibre 'error' event, since the failure is a plain
  // Worker load error the library doesn't surface). This is dev-only --
  // `vite build`'s Rollup pipeline resolves the same worker import
  // correctly on its own. Excluding the package from pre-bundling serves
  // it as real ESM straight from node_modules in dev too, where the
  // worker's relative import resolves against the actual package files.
  optimizeDeps: {
    exclude: ["maplibre-gl"],
  },
  plugins: [
    tanstackStart(),
    nitro(),
    react(),
    tailwindcss(),
    tsconfigPaths(),
    VitePWA({
      // Manual registration (src/components/pwa/PwaUpdatePrompt.tsx) so the
      // update prompt can be offered via a toast instead of force-reloading
      // mid-checkout.
      injectRegister: false,
      registerType: "prompt",
      // Off by default in vite-plugin-pwa; opted in so manifest/SW can be
      // smoke-tested against `vite dev` too, not just the production build.
      devOptions: { enabled: true },
      manifest: {
        name: "LE PACHA RESTAURANT",
        short_name: "LE PACHA",
        description: "Application de commande du restaurant LE PACHA",
        lang: "fr",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        theme_color: "#32190c",
        background_color: "#faf6ee",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/icon-192-maskable.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
          { src: "/icons/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      // No `workbox` option here: TanStack Start builds through Vite's
      // Environment API (a client + an ssr build in one `vite build`), and
      // this plugin's own service-worker generation only fires when its
      // captured config satisfies a single-environment `build.ssr === false`
      // check that never holds in either environment here -- so `sw.js`
      // silently never gets written. `manifest.webmanifest` above is
      // unaffected (it's an unconditional `generateBundle` hook) and is
      // confirmed working. The actual service worker is generated by
      // `scripts/generate-sw.mjs` (same workbox-build API this plugin would
      // have called) as a postbuild step -- see `npm run build`.
    }),
  ],
});
