import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  plugins: [
    tanstackStart(),
    react(),
    tailwindcss(),
    tsconfigPaths(),
    VitePWA({
      // Manual registration (src/components/pwa/PwaUpdatePrompt.tsx) so the
      // update prompt can be offered via a toast instead of force-reloading
      // mid-checkout.
      injectRegister: false,
      registerType: "prompt",
      // Off by default in vite-plugin-pwa; opted in so manifest/SW can be
      // smoke-tested against `vite dev` too, not just the production build.
      devOptions: { enabled: true },
      manifest: {
        name: "LE PACHA RESTAURANT",
        short_name: "LE PACHA",
        description: "Application de commande du restaurant LE PACHA",
        lang: "fr",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        theme_color: "#32190c",
        background_color: "#faf6ee",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/icon-192-maskable.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
          { src: "/icons/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      // No `workbox` option here: TanStack Start builds through Vite's
      // Environment API (a client + an ssr build in one `vite build`), and
      // this plugin's own service-worker generation only fires when its
      // captured config satisfies a single-environment `build.ssr === false`
      // check that never holds in either environment here -- so `sw.js`
      // silently never gets written. `manifest.webmanifest` above is
      // unaffected (it's an unconditional `generateBundle` hook) and is
      // confirmed working. The actual service worker is generated by
      // `scripts/generate-sw.mjs` (same workbox-build API this plugin would
      // have called) as a postbuild step -- see `npm run build`.
    }),
  ],
});
