import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  // `npm run dev` (plain `vite dev`) binds to localhost only by default --
  // LAN origins like http://192.168.1.79:5173 need this to be reachable
  // without manually passing --host every time.
  server: {
    host: true,
  },
  optimizeDeps: {
    // maplibre-gl loads its own worker as a sibling module
    // (maplibre-gl-worker.mjs) resolved relative to its own module URL. Vite
    // dev's esbuild pre-bundler only pre-bundles the main "maplibre-gl"
    // entry into node_modules/.vite/deps/, never that worker sub-module, so
    // the sibling path it computes 404s there and the worker never gets its
    // code -- the map then sits on a correctly-sized, empty WebGL canvas
    // (style/sprites/tiles-source all fetch fine; zero .pbf tile requests
    // ever fire since tile loading is gated on the worker). Excluding it
    // here makes Vite serve it straight from node_modules instead, where
    // its relative worker path resolves for real. Production builds are
    // unaffected (Rollup inlines the worker code into the bundle instead).
    exclude: ["maplibre-gl"],
  },
  plugins: [
    tanstackStart(),
    react(),
    tailwindcss(),
    tsconfigPaths(),
    VitePWA({
      // Manual registration (src/components/pwa/PwaUpdatePrompt.tsx) so the
      // update prompt can be offered via a toast instead of force-reloading
      // mid-checkout.
      injectRegister: false,
      registerType: "prompt",
      // Off by default in vite-plugin-pwa; opted in so manifest/SW can be
      // smoke-tested against `vite dev` too, not just the production build.
      devOptions: { enabled: true },
      manifest: {
        name: "SAOVIA Food",
        short_name: "SAOVIA Food",
        description: "SAOVIA Food : menu digital, commande en ligne et livraison pour restaurants.",
        lang: "fr",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        theme_color: "#32190c",
        background_color: "#ffffff",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/icon-192-maskable.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
          { src: "/icons/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      // No `workbox` option here: TanStack Start builds through Vite's
      // Environment API (a client + an ssr build in one `vite build`), and
      // this plugin's own service-worker generation only fires when its
      // captured config satisfies a single-environment `build.ssr === false`
      // check that never holds in either environment here -- so `sw.js`
      // silently never gets written. `manifest.webmanifest` above is
      // unaffected (it's an unconditional `generateBundle` hook) and is
      // confirmed working. The actual service worker is generated by
      // `scripts/generate-sw.mjs` (same workbox-build API this plugin would
      // have called) as a postbuild step -- see `npm run build`.
    }),
  ],
});
