/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as RechercherRouteImport } from './routes/rechercher'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as RestaurantSlugRouteImport } from './routes/restaurant.$slug'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as CommandeOrderIdConfirmationRouteImport } from './routes/commande.$orderId.confirmation'
import { Route as RestaurantsCategorieCategorySlugRouteImport } from './routes/restaurants.categorie.$categorySlug'
import { Route as SuperAdminRestaurantsRestaurantIdRouteImport } from './routes/super-admin.restaurants.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercherRoute = RechercherRouteImport.update({
  id: '/rechercher',
  path: '/rechercher',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSlugRoute = RestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const CommandeOrderIdConfirmationRoute =
  CommandeOrderIdConfirmationRouteImport.update({
    id: '/commande/$orderId/confirmation',
    path: '/commande/$orderId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsCategorieCategorySlugRoute =
  RestaurantsCategorieCategorySlugRouteImport.update({
    id: '/categorie/$categorySlug',
    path: '/categorie/$categorySlug',
    getParentRoute: () => RestaurantsRoute,
  } as any)
const SuperAdminRestaurantsRestaurantIdRoute =
  SuperAdminRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => SuperAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/rechercher'
    | '/restaurants'
    | '/super-admin'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/super-admin/'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/restaurants/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/rechercher'
    | '/restaurants'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/super-admin'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/restaurants/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/rechercher'
    | '/restaurants'
    | '/super-admin'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/super-admin/'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/restaurants/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommandesRoute: typeof CommandesRoute
  RechercherRoute: typeof RechercherRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  RSlugRoute: typeof RSlugRoute
  RestaurantSlugRoute: typeof RestaurantSlugRoute
  CommandeOrderIdConfirmationRoute: typeof CommandeOrderIdConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechercher': {
      id: '/rechercher'
      path: '/rechercher'
      fullPath: '/rechercher'
      preLoaderRoute: typeof RechercherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$slug': {
      id: '/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/restaurant/$slug'
      preLoaderRoute: typeof RestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/commande/$orderId/confirmation': {
      id: '/commande/$orderId/confirmation'
      path: '/commande/$orderId/confirmation'
      fullPath: '/commande/$orderId/confirmation'
      preLoaderRoute: typeof CommandeOrderIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/categorie/$categorySlug': {
      id: '/restaurants/categorie/$categorySlug'
      path: '/categorie/$categorySlug'
      fullPath: '/restaurants/categorie/$categorySlug'
      preLoaderRoute: typeof RestaurantsCategorieCategorySlugRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/super-admin/restaurants/$restaurantId': {
      id: '/super-admin/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/super-admin/restaurants/$restaurantId'
      preLoaderRoute: typeof SuperAdminRestaurantsRestaurantIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsCategorieCategorySlugRoute: typeof RestaurantsCategorieCategorySlugRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsCategorieCategorySlugRoute: RestaurantsCategorieCategorySlugRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminRestaurantsRestaurantIdRoute: typeof SuperAdminRestaurantsRestaurantIdRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminRestaurantsRestaurantIdRoute:
    SuperAdminRestaurantsRestaurantIdRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommandesRoute: CommandesRoute,
  RechercherRoute: RechercherRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  RSlugRoute: RSlugRoute,
  RestaurantSlugRoute: RestaurantSlugRoute,
  CommandeOrderIdConfirmationRoute: CommandeOrderIdConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
