/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as DeliverRouteImport } from './routes/deliver'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as LivreurRouteImport } from './routes/livreur'
import { Route as RechercherRouteImport } from './routes/rechercher'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as DeliveryIdRouteImport } from './routes/delivery.$id'
import { Route as DeliveryDashboardRouteImport } from './routes/delivery.dashboard'
import { Route as DeliveryLoginRouteImport } from './routes/delivery.login'
import { Route as DeliveryNewRouteImport } from './routes/delivery.new'
import { Route as DeliverySignupRouteImport } from './routes/delivery.signup'
import { Route as LivreurActivationRouteImport } from './routes/livreur.activation'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as RestaurantSlugRouteImport } from './routes/restaurant.$slug'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminMarketingRouteImport } from './routes/super-admin.marketing'
import { Route as CommandeOrderIdConfirmationRouteImport } from './routes/commande.$orderId.confirmation'
import { Route as RestaurantsCategorieCategorySlugRouteImport } from './routes/restaurants.categorie.$categorySlug'
import { Route as SuperAdminMarketingIndexRouteImport } from './routes/super-admin.marketing.index'
import { Route as SuperAdminMarketingAudiencesRouteImport } from './routes/super-admin.marketing.audiences'
import { Route as SuperAdminMarketingCampagnesRouteImport } from './routes/super-admin.marketing.campagnes'
import { Route as SuperAdminRestaurantsRestaurantIdRouteImport } from './routes/super-admin.restaurants.$restaurantId'
import { Route as SuperAdminMarketingCampagnesNouvelleRouteImport } from './routes/super-admin.marketing.campagnes_.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverRoute = DeliverRouteImport.update({
  id: '/deliver',
  path: '/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRoute = LivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercherRoute = RechercherRouteImport.update({
  id: '/rechercher',
  path: '/rechercher',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryIdRoute = DeliveryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryDashboardRoute = DeliveryDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryLoginRoute = DeliveryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryNewRoute = DeliveryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliverySignupRoute = DeliverySignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DeliveryRoute,
} as any)
const LivreurActivationRoute = LivreurActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => LivreurRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSlugRoute = RestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminMarketingRoute = SuperAdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => SuperAdminRoute,
} as any)
const CommandeOrderIdConfirmationRoute =
  CommandeOrderIdConfirmationRouteImport.update({
    id: '/commande/$orderId/confirmation',
    path: '/commande/$orderId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsCategorieCategorySlugRoute =
  RestaurantsCategorieCategorySlugRouteImport.update({
    id: '/categorie/$categorySlug',
    path: '/categorie/$categorySlug',
    getParentRoute: () => RestaurantsRoute,
  } as any)
const SuperAdminMarketingIndexRoute =
  SuperAdminMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SuperAdminMarketingRoute,
  } as any)
const SuperAdminMarketingAudiencesRoute =
  SuperAdminMarketingAudiencesRouteImport.update({
    id: '/audiences',
    path: '/audiences',
    getParentRoute: () => SuperAdminMarketingRoute,
  } as any)
const SuperAdminMarketingCampagnesRoute =
  SuperAdminMarketingCampagnesRouteImport.update({
    id: '/campagnes',
    path: '/campagnes',
    getParentRoute: () => SuperAdminMarketingRoute,
  } as any)
const SuperAdminRestaurantsRestaurantIdRoute =
  SuperAdminRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminMarketingCampagnesNouvelleRoute =
  SuperAdminMarketingCampagnesNouvelleRouteImport.update({
    id: '/campagnes_/nouvelle',
    path: '/campagnes/nouvelle',
    getParentRoute: () => SuperAdminMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/deliver': typeof DeliverRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/livreur': typeof LivreurRouteWithChildren
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/delivery/$id': typeof DeliveryIdRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/signup': typeof DeliverySignupRoute
  '/livreur/activation': typeof LivreurActivationRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/super-admin/marketing': typeof SuperAdminMarketingRouteWithChildren
  '/delivery/': typeof DeliveryIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/marketing/audiences': typeof SuperAdminMarketingAudiencesRoute
  '/super-admin/marketing/campagnes': typeof SuperAdminMarketingCampagnesRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
  '/super-admin/marketing/': typeof SuperAdminMarketingIndexRoute
  '/super-admin/marketing/campagnes/nouvelle': typeof SuperAdminMarketingCampagnesNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/deliver': typeof DeliverRoute
  '/livreur': typeof LivreurRouteWithChildren
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/delivery/$id': typeof DeliveryIdRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/signup': typeof DeliverySignupRoute
  '/livreur/activation': typeof LivreurActivationRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/delivery': typeof DeliveryIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/marketing/audiences': typeof SuperAdminMarketingAudiencesRoute
  '/super-admin/marketing/campagnes': typeof SuperAdminMarketingCampagnesRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
  '/super-admin/marketing': typeof SuperAdminMarketingIndexRoute
  '/super-admin/marketing/campagnes/nouvelle': typeof SuperAdminMarketingCampagnesNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/commandes': typeof CommandesRoute
  '/deliver': typeof DeliverRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/livreur': typeof LivreurRouteWithChildren
  '/rechercher': typeof RechercherRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/delivery/$id': typeof DeliveryIdRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/signup': typeof DeliverySignupRoute
  '/livreur/activation': typeof LivreurActivationRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/super-admin/marketing': typeof SuperAdminMarketingRouteWithChildren
  '/delivery/': typeof DeliveryIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/commande/$orderId/confirmation': typeof CommandeOrderIdConfirmationRoute
  '/restaurants/categorie/$categorySlug': typeof RestaurantsCategorieCategorySlugRoute
  '/super-admin/marketing/audiences': typeof SuperAdminMarketingAudiencesRoute
  '/super-admin/marketing/campagnes': typeof SuperAdminMarketingCampagnesRoute
  '/super-admin/restaurants/$restaurantId': typeof SuperAdminRestaurantsRestaurantIdRoute
  '/super-admin/marketing/': typeof SuperAdminMarketingIndexRoute
  '/super-admin/marketing/campagnes_/nouvelle': typeof SuperAdminMarketingCampagnesNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/deliver'
    | '/delivery'
    | '/livreur'
    | '/rechercher'
    | '/restaurants'
    | '/super-admin'
    | '/delivery/$id'
    | '/delivery/dashboard'
    | '/delivery/login'
    | '/delivery/new'
    | '/delivery/signup'
    | '/livreur/activation'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/super-admin/marketing'
    | '/delivery/'
    | '/super-admin/'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/marketing/audiences'
    | '/super-admin/marketing/campagnes'
    | '/super-admin/restaurants/$restaurantId'
    | '/super-admin/marketing/'
    | '/super-admin/marketing/campagnes/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/deliver'
    | '/livreur'
    | '/rechercher'
    | '/restaurants'
    | '/delivery/$id'
    | '/delivery/dashboard'
    | '/delivery/login'
    | '/delivery/new'
    | '/delivery/signup'
    | '/livreur/activation'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/delivery'
    | '/super-admin'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/marketing/audiences'
    | '/super-admin/marketing/campagnes'
    | '/super-admin/restaurants/$restaurantId'
    | '/super-admin/marketing'
    | '/super-admin/marketing/campagnes/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/commandes'
    | '/deliver'
    | '/delivery'
    | '/livreur'
    | '/rechercher'
    | '/restaurants'
    | '/super-admin'
    | '/delivery/$id'
    | '/delivery/dashboard'
    | '/delivery/login'
    | '/delivery/new'
    | '/delivery/signup'
    | '/livreur/activation'
    | '/r/$slug'
    | '/restaurant/$slug'
    | '/super-admin/marketing'
    | '/delivery/'
    | '/super-admin/'
    | '/commande/$orderId/confirmation'
    | '/restaurants/categorie/$categorySlug'
    | '/super-admin/marketing/audiences'
    | '/super-admin/marketing/campagnes'
    | '/super-admin/restaurants/$restaurantId'
    | '/super-admin/marketing/'
    | '/super-admin/marketing/campagnes_/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommandesRoute: typeof CommandesRoute
  DeliverRoute: typeof DeliverRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  LivreurRoute: typeof LivreurRouteWithChildren
  RechercherRoute: typeof RechercherRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  RSlugRoute: typeof RSlugRoute
  RestaurantSlugRoute: typeof RestaurantSlugRoute
  CommandeOrderIdConfirmationRoute: typeof CommandeOrderIdConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliver': {
      id: '/deliver'
      path: '/deliver'
      fullPath: '/deliver'
      preLoaderRoute: typeof DeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechercher': {
      id: '/rechercher'
      path: '/rechercher'
      fullPath: '/rechercher'
      preLoaderRoute: typeof RechercherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/$id': {
      id: '/delivery/$id'
      path: '/$id'
      fullPath: '/delivery/$id'
      preLoaderRoute: typeof DeliveryIdRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/dashboard': {
      id: '/delivery/dashboard'
      path: '/dashboard'
      fullPath: '/delivery/dashboard'
      preLoaderRoute: typeof DeliveryDashboardRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/login': {
      id: '/delivery/login'
      path: '/login'
      fullPath: '/delivery/login'
      preLoaderRoute: typeof DeliveryLoginRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/new': {
      id: '/delivery/new'
      path: '/new'
      fullPath: '/delivery/new'
      preLoaderRoute: typeof DeliveryNewRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/signup': {
      id: '/delivery/signup'
      path: '/signup'
      fullPath: '/delivery/signup'
      preLoaderRoute: typeof DeliverySignupRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/livreur/activation': {
      id: '/livreur/activation'
      path: '/activation'
      fullPath: '/livreur/activation'
      preLoaderRoute: typeof LivreurActivationRouteImport
      parentRoute: typeof LivreurRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$slug': {
      id: '/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/restaurant/$slug'
      preLoaderRoute: typeof RestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/marketing': {
      id: '/super-admin/marketing'
      path: '/marketing'
      fullPath: '/super-admin/marketing'
      preLoaderRoute: typeof SuperAdminMarketingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/commande/$orderId/confirmation': {
      id: '/commande/$orderId/confirmation'
      path: '/commande/$orderId/confirmation'
      fullPath: '/commande/$orderId/confirmation'
      preLoaderRoute: typeof CommandeOrderIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/categorie/$categorySlug': {
      id: '/restaurants/categorie/$categorySlug'
      path: '/categorie/$categorySlug'
      fullPath: '/restaurants/categorie/$categorySlug'
      preLoaderRoute: typeof RestaurantsCategorieCategorySlugRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/super-admin/marketing/': {
      id: '/super-admin/marketing/'
      path: '/'
      fullPath: '/super-admin/marketing/'
      preLoaderRoute: typeof SuperAdminMarketingIndexRouteImport
      parentRoute: typeof SuperAdminMarketingRoute
    }
    '/super-admin/marketing/audiences': {
      id: '/super-admin/marketing/audiences'
      path: '/audiences'
      fullPath: '/super-admin/marketing/audiences'
      preLoaderRoute: typeof SuperAdminMarketingAudiencesRouteImport
      parentRoute: typeof SuperAdminMarketingRoute
    }
    '/super-admin/marketing/campagnes': {
      id: '/super-admin/marketing/campagnes'
      path: '/campagnes'
      fullPath: '/super-admin/marketing/campagnes'
      preLoaderRoute: typeof SuperAdminMarketingCampagnesRouteImport
      parentRoute: typeof SuperAdminMarketingRoute
    }
    '/super-admin/restaurants/$restaurantId': {
      id: '/super-admin/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/super-admin/restaurants/$restaurantId'
      preLoaderRoute: typeof SuperAdminRestaurantsRestaurantIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/marketing/campagnes_/nouvelle': {
      id: '/super-admin/marketing/campagnes_/nouvelle'
      path: '/campagnes/nouvelle'
      fullPath: '/super-admin/marketing/campagnes/nouvelle'
      preLoaderRoute: typeof SuperAdminMarketingCampagnesNouvelleRouteImport
      parentRoute: typeof SuperAdminMarketingRoute
    }
  }
}

interface DeliveryRouteChildren {
  DeliveryIdRoute: typeof DeliveryIdRoute
  DeliveryDashboardRoute: typeof DeliveryDashboardRoute
  DeliveryLoginRoute: typeof DeliveryLoginRoute
  DeliveryNewRoute: typeof DeliveryNewRoute
  DeliverySignupRoute: typeof DeliverySignupRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryIdRoute: DeliveryIdRoute,
  DeliveryDashboardRoute: DeliveryDashboardRoute,
  DeliveryLoginRoute: DeliveryLoginRoute,
  DeliveryNewRoute: DeliveryNewRoute,
  DeliverySignupRoute: DeliverySignupRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface LivreurRouteChildren {
  LivreurActivationRoute: typeof LivreurActivationRoute
}

const LivreurRouteChildren: LivreurRouteChildren = {
  LivreurActivationRoute: LivreurActivationRoute,
}

const LivreurRouteWithChildren =
  LivreurRoute._addFileChildren(LivreurRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsCategorieCategorySlugRoute: typeof RestaurantsCategorieCategorySlugRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsCategorieCategorySlugRoute: RestaurantsCategorieCategorySlugRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface SuperAdminMarketingRouteChildren {
  SuperAdminMarketingAudiencesRoute: typeof SuperAdminMarketingAudiencesRoute
  SuperAdminMarketingCampagnesRoute: typeof SuperAdminMarketingCampagnesRoute
  SuperAdminMarketingIndexRoute: typeof SuperAdminMarketingIndexRoute
  SuperAdminMarketingCampagnesNouvelleRoute: typeof SuperAdminMarketingCampagnesNouvelleRoute
}

const SuperAdminMarketingRouteChildren: SuperAdminMarketingRouteChildren = {
  SuperAdminMarketingAudiencesRoute: SuperAdminMarketingAudiencesRoute,
  SuperAdminMarketingCampagnesRoute: SuperAdminMarketingCampagnesRoute,
  SuperAdminMarketingIndexRoute: SuperAdminMarketingIndexRoute,
  SuperAdminMarketingCampagnesNouvelleRoute:
    SuperAdminMarketingCampagnesNouvelleRoute,
}

const SuperAdminMarketingRouteWithChildren =
  SuperAdminMarketingRoute._addFileChildren(SuperAdminMarketingRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminMarketingRoute: typeof SuperAdminMarketingRouteWithChildren
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminRestaurantsRestaurantIdRoute: typeof SuperAdminRestaurantsRestaurantIdRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminMarketingRoute: SuperAdminMarketingRouteWithChildren,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminRestaurantsRestaurantIdRoute:
    SuperAdminRestaurantsRestaurantIdRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommandesRoute: CommandesRoute,
  DeliverRoute: DeliverRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  LivreurRoute: LivreurRouteWithChildren,
  RechercherRoute: RechercherRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  RSlugRoute: RSlugRoute,
  RestaurantSlugRoute: RestaurantSlugRoute,
  CommandeOrderIdConfirmationRoute: CommandeOrderIdConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
